# 7
# streamlit run app.py

import os
import joblib
import numpy as np
import pandas as pd
import streamlit as st


# =========================
# Page Config
# =========================

st.set_page_config(
    page_title="Travel Recommendation System",
    layout="wide"
)

st.title("旅遊地點推薦系統")
st.caption("Preference-based Clustering + Cluster-based Recommendation Demo")


# =========================
# Load Data
# =========================

@st.cache_data
def load_csv_data():

    user_df = pd.read_csv("data/travel_behavior_soft_clustered.csv")
    attractions = pd.read_csv("data/attractions.csv")

    method_comparison = None

    if os.path.exists("data/recommendation_method_comparison.csv"):

        method_comparison = pd.read_csv(
            "data/recommendation_method_comparison.csv"
        )

    cluster_interpretation = None

    if os.path.exists("data/soft_cluster_interpretation.csv"):

        cluster_interpretation = pd.read_csv(
            "data/soft_cluster_interpretation.csv"
        )

    cluster_label_summary = None

    if os.path.exists("data/soft_cluster_label_summary.csv"):

        cluster_label_summary = pd.read_csv(
            "data/soft_cluster_label_summary.csv"
        )

    return (
        user_df,
        attractions,
        method_comparison,
        cluster_interpretation,
        cluster_label_summary
    )


@st.cache_resource
def load_cluster_model():

    return joblib.load("models/soft_cluster_pipeline.pkl")


(
    user_df,
    attractions,
    method_comparison,
    cluster_interpretation,
    cluster_label_summary
) = load_csv_data()

cluster_model = load_cluster_model()


# =========================
# Basic Settings
# =========================

behavior_features = [
    "selected_indoor_score",
    "selected_cost_level",
    "selected_photo_value",
    "selected_nature_value",
    "selected_culture_value",
    "selected_food_value",
    "selected_popularity"
]

attraction_features = [
    "indoor_score",
    "cost_level",
    "photo_value",
    "nature_value",
    "culture_value",
    "food_value",
    "popularity"
]



# =========================
# Cluster Labels and Descriptions
# =========================

FEATURE_DISPLAY_NAMES = {
    "budget": "預算",
    "available_time": "可用時間",
    "weather_badness": "天氣不佳程度",
    "social_context": "同行／社交情境",
    "fatigue": "疲勞程度",
    "spontaneity": "隨興程度",
    "selected_indoor_score": "室內偏好",
    "selected_cost_level": "消費等級偏好",
    "selected_photo_value": "拍照價值偏好",
    "selected_nature_value": "自然景觀偏好",
    "selected_culture_value": "文化價值偏好",
    "selected_food_value": "美食價值偏好",
    "selected_popularity": "熱門程度偏好",
}


# Fallback labels are used only when data/soft_cluster_label_summary.csv is missing.
# The main source should be generated by cluster_interpretation_soft.py after clustering.
FALLBACK_CLUSTER_LABELS = {
    0: "Cluster 0",
    1: "Cluster 1",
    2: "Cluster 2",
    3: "Cluster 3",
    4: "Cluster 4",
    5: "Cluster 5",
    6: "Cluster 6",
    7: "Cluster 7",
}

FALLBACK_CLUSTER_DESCRIPTIONS = {
    0: "尚未載入 data/soft_cluster_label_summary.csv，僅顯示 cluster 編號。",
    1: "尚未載入 data/soft_cluster_label_summary.csv，僅顯示 cluster 編號。",
    2: "尚未載入 data/soft_cluster_label_summary.csv，僅顯示 cluster 編號。",
    3: "尚未載入 data/soft_cluster_label_summary.csv，僅顯示 cluster 編號。",
    4: "尚未載入 data/soft_cluster_label_summary.csv，僅顯示 cluster 編號。",
    5: "尚未載入 data/soft_cluster_label_summary.csv，僅顯示 cluster 編號。",
    6: "尚未載入 data/soft_cluster_label_summary.csv，僅顯示 cluster 編號。",
    7: "尚未載入 data/soft_cluster_label_summary.csv，僅顯示 cluster 編號。",
}


def get_cluster_label_row(cluster_id):

    if cluster_label_summary is None:
        return None

    if "cluster" not in cluster_label_summary.columns:
        return None

    matched = cluster_label_summary[
        cluster_label_summary["cluster"].astype(int) == int(cluster_id)
    ]

    if matched.empty:
        return None

    return matched.iloc[0]


def get_cluster_label(cluster_id):

    row = get_cluster_label_row(cluster_id)

    if row is not None and "cluster_label" in row.index and pd.notna(row["cluster_label"]):
        return str(row["cluster_label"])

    return FALLBACK_CLUSTER_LABELS.get(
        int(cluster_id),
        f"Cluster {int(cluster_id)}"
    )


def get_cluster_description(cluster_id):

    row = get_cluster_label_row(cluster_id)

    if row is not None:
        description_parts = []

        if "description" in row.index and pd.notna(row["description"]):
            description_parts.append(str(row["description"]))

        if "label_basis" in row.index and pd.notna(row["label_basis"]):
            description_parts.append(str(row["label_basis"]))

        if "label_strength" in row.index and pd.notna(row["label_strength"]):
            description_parts.append(f"Label strength：{row['label_strength']}")

        if description_parts:
            return "\n\n".join(description_parts)

    return FALLBACK_CLUSTER_DESCRIPTIONS.get(
        int(cluster_id),
        "目前尚未定義此 cluster 的語意解釋。"
    )


def format_cluster_title(cluster_id):

    return f"Cluster {int(cluster_id)}：{get_cluster_label(cluster_id)}"


def get_confidence_level(confidence):

    if confidence >= 0.70:
        return (
            "High",
            "模型對此 cluster 判斷信心較高，可主要參考目前的 cluster label 與推薦結果。"
        )

    if confidence >= 0.40:
        return (
            "Medium",
            "模型對此 cluster 判斷信心中等，建議同時參考 Top probability clusters。"
        )

    return (
        "Low",
        "模型對此 cluster 判斷信心偏低，代表使用者偏好可能分散於多個 cluster，不建議只依賴單一 label。"
    )


# =========================
# Helper Functions
# =========================

def cosine_similarity(a, b):

    a = np.array(a, dtype=float)
    b = np.array(b, dtype=float)

    denom = np.linalg.norm(a) * np.linalg.norm(b)

    if denom == 0:
        return 0.0

    return float(np.dot(a, b) / denom)



def build_realistic_scene_name(spot):

    if "realistic_scene_name" in spot.index and pd.notna(spot["realistic_scene_name"]):
        return str(spot["realistic_scene_name"])

    if "name" in spot.index and pd.notna(spot["name"]):
        return str(spot["name"])

    attraction_type = str(spot.get("attraction_type", "attraction"))
    attraction_id = int(spot.get("attraction_id", 0))

    type_name_map = {
        "museum": "博物館",
        "gallery": "藝文展覽空間",
        "park": "公園",
        "viewpoint": "觀景景點",
        "tourism": "觀光景點",
        "restaurant": "餐廳",
        "cafe": "咖啡廳",
        "market": "市集",
        "shopping": "購物景點",
        "historic": "歷史景點",
        "temple": "宗教文化景點",
        "library": "圖書館",
        "theatre": "劇場",
        "cinema": "電影院",
    }

    readable_type = type_name_map.get(attraction_type, attraction_type)
    return f"{readable_type}_{attraction_id:03d}"


def get_cluster_only_recommendations(
    cluster_id,
    top_k,
    cluster_behavior,
    attractions_df
):

    cluster_vec = cluster_behavior.loc[cluster_id].values

    rows = []

    for _, spot in attractions_df.iterrows():

        spot_vec = spot[attraction_features].values

        score = cosine_similarity(
            cluster_vec,
            spot_vec
        )

        rows.append({
            "scene_name": build_realistic_scene_name(spot),
            "name": spot["name"],
            "attraction_type": spot["attraction_type"],
            "cluster_score": score,
            "recommendation_score": score,
            "cost_level": spot["cost_level"],
            "indoor_score": spot["indoor_score"],
            "photo_value": spot["photo_value"],
            "nature_value": spot["nature_value"],
            "culture_value": spot["culture_value"],
            "food_value": spot["food_value"],
            "popularity": spot["popularity"],
            "estimated_time": spot["estimated_time"]
        })

    result = pd.DataFrame(rows)

    return (
        result
        .sort_values(
            "recommendation_score",
            ascending=False
        )
        .head(top_k)
    )


def predict_soft_cluster(input_data, cluster_model):

    features = cluster_model["features"]
    imputer = cluster_model["imputer"]
    scaler = cluster_model["scaler"]
    gmm = cluster_model["gmm"]

    input_df = pd.DataFrame([input_data])

    missing_features = [
        feature for feature in features
        if feature not in input_df.columns
    ]

    if len(missing_features) > 0:

        raise ValueError(
            "模型需要的欄位不存在，請確認 soft_cluster_pipeline.pkl 是否為新版。"
            f" 缺少欄位：{missing_features}"
        )

    X_input = input_df[features]

    X_imputed = imputer.transform(X_input)
    X_scaled = scaler.transform(X_imputed)

    cluster_probs = gmm.predict_proba(X_scaled)[0]

    predicted_cluster = int(np.argmax(cluster_probs))
    cluster_confidence = float(np.max(cluster_probs))

    return predicted_cluster, cluster_confidence, cluster_probs



# 若 attractions.csv 是舊版資料，沒有 realistic_scene_name 欄位，App 會自動補上較接近現實場景的顯示名稱。
if "realistic_scene_name" not in attractions.columns:
    attractions["realistic_scene_name"] = attractions.apply(
        build_realistic_scene_name,
        axis=1
    )

# =========================
# Cluster Behavior Prototype
# =========================

cluster_behavior = (
    user_df
    .groupby("soft_cluster")[behavior_features]
    .mean()
)


# =========================
# Sidebar
# =========================

st.sidebar.header("系統設定")

top_k = st.sidebar.slider(
    "顯示推薦數量",
    min_value=1,
    max_value=10,
    value=5
)

st.sidebar.header("使用者輸入方式")

manual_mode = st.sidebar.checkbox(
    "使用手動輸入模式",
    value=True
)




# =========================
# Sidebar Input Labels
# =========================

INPUT_FIELD_INFO = {
    "budget": {
        "label": "旅遊預算 (Budget)",
        "meaning": "低：預算有限，偏向低消費景點；高：預算充足，可接受高消費景點。",
    },
    "available_time": {
        "label": "可用時間 (Available Time)",
        "meaning": "低：停留時間短，適合快速參觀；高：時間充足，適合深度體驗。",
    },
    "weather_badness": {
        "label": "天氣不佳程度 (Weather Badness)",
        "meaning": "低：天氣良好，戶外景點可行；高：天氣較差，較適合室內或遮蔽性高的景點。",
    },
    "social_context": {
        "label": "同行／社交情境 (Social Context)",
        "meaning": "低：偏向個人或安靜行程；高：偏向多人同行、社交性或熱門景點。",
    },
    "fatigue": {
        "label": "疲勞程度 (Fatigue)",
        "meaning": "低：體力充足，可接受較長或較耗體力行程；高：較疲勞，適合輕鬆、短時間或室內景點。",
    },
    "spontaneity": {
        "label": "隨興程度 (Spontaneity)",
        "meaning": "低：偏好明確規劃、穩定行程；高：偏好彈性、臨時決定或探索型行程。",
    },
    "selected_indoor_score": {
        "label": "室內偏好 (Indoor Preference)",
        "meaning": "低：偏好戶外景點；高：偏好室內景點，例如博物館、展覽、咖啡廳。",
    },
    "selected_cost_level": {
        "label": "消費等級偏好 (Cost Level)",
        "meaning": "低：偏好低消費或免費景點；高：可接受高消費、門票或商業型景點。",
    },
    "selected_photo_value": {
        "label": "拍照價值偏好 (Photo Value)",
        "meaning": "低：不重視拍照或打卡；高：重視景觀、視覺特色與拍照效果。",
    },
    "selected_nature_value": {
        "label": "自然景觀偏好 (Nature Value)",
        "meaning": "低：不特別偏好自然景點；高：偏好公園、山景、水岸、自然步道。",
    },
    "selected_culture_value": {
        "label": "文化價值偏好 (Culture Value)",
        "meaning": "低：不特別偏好文化歷史；高：偏好博物館、古蹟、老街、藝文空間。",
    },
    "selected_food_value": {
        "label": "美食價值偏好 (Food Value)",
        "meaning": "低：不以餐飲為主要目的；高：偏好餐廳、咖啡廳、夜市或美食街。",
    },
    "selected_popularity": {
        "label": "熱門程度偏好 (Popularity)",
        "meaning": "低：偏好小眾、安靜景點；高：偏好熱門、知名、社群討論度高的景點。",
    },
}


def sidebar_number_input_with_meaning(field_key, **kwargs):
    info = INPUT_FIELD_INFO[field_key]
    value = st.sidebar.number_input(
        info["label"],
        help=info["meaning"],
        **kwargs
    )
    st.sidebar.caption(info["meaning"])
    return value


def sidebar_slider_with_meaning(field_key, **kwargs):
    info = INPUT_FIELD_INFO[field_key]
    value = st.sidebar.slider(
        info["label"],
        help=info["meaning"],
        **kwargs
    )
    st.sidebar.caption(info["meaning"])
    return value


# =========================
# Manual Input Mode
# =========================

input_data = None
selected_user = None
predicted_cluster = None
cluster_confidence = None
cluster_probs = None

if manual_mode:

    st.sidebar.header("手動輸入使用者條件")

    input_data = {}

    input_data["budget"] = sidebar_number_input_with_meaning(
        "budget",
        min_value=100.0,
        max_value=5000.0,
        value=800.0,
        step=100.0
    )

    input_data["available_time"] = sidebar_number_input_with_meaning(
        "available_time",
        min_value=1.0,
        max_value=12.0,
        value=5.0,
        step=0.5
    )

    input_data["weather_badness"] = sidebar_slider_with_meaning(
        "weather_badness",
        min_value=0.0,
        max_value=1.0,
        value=0.3,
        step=0.05
    )

    input_data["social_context"] = sidebar_slider_with_meaning(
        "social_context",
        min_value=0.0,
        max_value=1.0,
        value=0.5,
        step=0.05
    )

    input_data["fatigue"] = sidebar_slider_with_meaning(
        "fatigue",
        min_value=0.0,
        max_value=5.0,
        value=2.5,
        step=0.1
    )

    input_data["spontaneity"] = sidebar_slider_with_meaning(
        "spontaneity",
        min_value=0.0,
        max_value=5.0,
        value=2.5,
        step=0.1
    )

    input_data["selected_indoor_score"] = sidebar_slider_with_meaning(
        "selected_indoor_score",
        min_value=0.0,
        max_value=5.0,
        value=2.5,
        step=0.1
    )

    input_data["selected_cost_level"] = sidebar_slider_with_meaning(
        "selected_cost_level",
        min_value=0.0,
        max_value=5.0,
        value=2.5,
        step=0.1
    )

    input_data["selected_photo_value"] = sidebar_slider_with_meaning(
        "selected_photo_value",
        min_value=0.0,
        max_value=5.0,
        value=2.5,
        step=0.1
    )

    input_data["selected_nature_value"] = sidebar_slider_with_meaning(
        "selected_nature_value",
        min_value=0.0,
        max_value=5.0,
        value=2.5,
        step=0.1
    )

    input_data["selected_culture_value"] = sidebar_slider_with_meaning(
        "selected_culture_value",
        min_value=0.0,
        max_value=5.0,
        value=2.5,
        step=0.1
    )

    input_data["selected_food_value"] = sidebar_slider_with_meaning(
        "selected_food_value",
        min_value=0.0,
        max_value=5.0,
        value=2.5,
        step=0.1
    )

    input_data["selected_popularity"] = sidebar_slider_with_meaning(
        "selected_popularity",
        min_value=0.0,
        max_value=5.0,
        value=2.5,
        step=0.1
    )

    try:

        (
            predicted_cluster,
            cluster_confidence,
            cluster_probs
        ) = predict_soft_cluster(
            input_data,
            cluster_model
        )

        selected_user = pd.Series(input_data)
        selected_user["soft_cluster"] = predicted_cluster
        selected_user["soft_cluster_confidence"] = cluster_confidence

    except Exception as e:

        st.error(str(e))
        st.stop()

else:

    st.sidebar.header("既有使用者選擇")

    user_ids = sorted(user_df["user_id"].unique())

    selected_user_id = st.sidebar.selectbox(
        "選擇使用者 ID",
        user_ids
    )

    selected_user = user_df[
        user_df["user_id"] == selected_user_id
    ].iloc[0]

    predicted_cluster = int(selected_user["soft_cluster"])
    cluster_confidence = float(
        selected_user["soft_cluster_confidence"]
    )


# =========================
# User Info
# =========================

st.subheader("使用者資訊")

current_cluster_id = int(selected_user["soft_cluster"])
current_cluster_label = get_cluster_label(current_cluster_id)
current_cluster_description = get_cluster_description(current_cluster_id)

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        "Soft Cluster",
        current_cluster_id
    )

with col2:
    st.metric(
        "Cluster 類型",
        current_cluster_label
    )

with col3:
    st.metric(
        "Cluster Confidence",
        f"{selected_user['soft_cluster_confidence']:.3f}"
    )

with col4:
    st.metric(
        "Budget",
        f"{selected_user['budget']:.1f}"
    )

st.markdown("### 決策系統判定結果")
st.info(
    f"目前系統判定此使用者屬於 **{format_cluster_title(current_cluster_id)}**。"
    f"{current_cluster_description}"
)

cluster_summary_df = pd.DataFrame([
    {
        "cluster": current_cluster_id,
        "cluster_label": current_cluster_label,
        "confidence": float(selected_user["soft_cluster_confidence"]),
        "description": current_cluster_description,
    }
])

st.dataframe(
    cluster_summary_df,
    width="stretch",
    hide_index=True
)

confidence_level, confidence_message = get_confidence_level(
    selected_user["soft_cluster_confidence"]
)

st.markdown("### 模型信心判讀")

confidence_df = pd.DataFrame([
    {
        "confidence_level": confidence_level,
        "confidence": float(selected_user["soft_cluster_confidence"]),
        "interpretation": confidence_message,
    }
])

st.dataframe(
    confidence_df,
    width="stretch",
    hide_index=True
)

if confidence_level == "低信心":
    st.warning(
        "此使用者的 cluster confidence 較低。建議同時查看 Soft Cluster Probability 中的前幾個 cluster，"
        "不要只把推薦結果解釋為單一 cluster 的偏好。"
    )
elif confidence_level == "中等信心":
    st.info(
        "此使用者仍可能同時具有其他 cluster 的偏好特徵。"
    )

st.markdown("### Cluster 計算流程說明")

with st.expander("查看模型如何計算 Soft Cluster", expanded=False):

    st.write(
        "本系統的 cluster 不是人工規則直接分類，而是由 Gaussian Mixture Model 根據使用者的景點偏好特徵計算機率後決定。預算、天氣、疲勞與時間不再用來定義 cluster，避免情境欄位蓋過真正的景點偏好。"
    )

    st.markdown(
        """
計算流程如下：

1. 讀取使用者輸入特徵，例如室內偏好、消費等級偏好、拍照價值偏好、自然景觀偏好、文化價值偏好、美食價值偏好與熱門程度偏好。
2. 使用訓練時儲存的 imputer 補齊缺失值。
3. 使用訓練時儲存的 StandardScaler 將不同尺度的欄位轉成標準化數值。
4. 將標準化後的特徵輸入 GMM。
5. GMM 計算使用者屬於每個 cluster 的 probability。
6. probability 最高的 cluster 會被顯示為 Soft Cluster。
7. 最高 probability 會被視為 Cluster Confidence。

因此，畫面上的 cluster label 是模型輸出的機率結果，而不是單純用 if-else 規則指定。
        """
    )

    st.write("模型實際使用的特徵：")

    model_features_df = pd.DataFrame({
        "feature": cluster_model["features"],
        "feature_name": [
            FEATURE_DISPLAY_NAMES.get(feature, feature)
            for feature in cluster_model["features"]
        ]
    })

    st.dataframe(
        model_features_df,
        width="stretch",
        hide_index=True
    )

    if manual_mode and cluster_probs is not None:
        top_prob_df = pd.DataFrame({
            "cluster": list(range(len(cluster_probs))),
            "cluster_label": [
                get_cluster_label(cluster_id)
                for cluster_id in range(len(cluster_probs))
            ],
            "probability": cluster_probs
        }).sort_values("probability", ascending=False).head(3)

        st.write("目前輸入最可能屬於的前三個 cluster：")
        st.dataframe(
            top_prob_df,
            width="stretch",
            hide_index=True
        )


if manual_mode and cluster_probs is not None:

    st.markdown("### Soft Cluster Probability")

    prob_df = pd.DataFrame({
        "cluster": list(range(len(cluster_probs))),
        "cluster_label": [
            get_cluster_label(cluster_id)
            for cluster_id in range(len(cluster_probs))
        ],
        "probability": cluster_probs
    })

    prob_df = prob_df.sort_values(
        "probability",
        ascending=False
    )

    st.dataframe(
        prob_df,
        width="stretch",
        hide_index=True
    )

    st.bar_chart(
        prob_df.set_index("cluster_label")["probability"]
    )


st.markdown("### 使用者輸入 / 行為特徵")

display_user_cols = [
    "weather_badness",
    "social_context",
    "fatigue",
    "spontaneity",
    "selected_indoor_score",
    "selected_cost_level",
    "selected_photo_value",
    "selected_nature_value",
    "selected_culture_value",
    "selected_food_value",
    "selected_popularity"
]

available_display_user_cols = [
    col for col in display_user_cols
    if col in selected_user.index
]

st.dataframe(
    selected_user[available_display_user_cols]
    .to_frame(name="value"),
    width="stretch",
    height=450
)


# =========================
# Cluster-based Recommendation
# =========================

st.subheader("Cluster-based 推薦景點")

st.info(
    "目前推薦只使用使用者所屬 cluster 的平均行為特徵，"
    "不直接用個人行為向量排序。"
)

cluster_id = int(selected_user["soft_cluster"])

if cluster_id not in cluster_behavior.index:

    st.warning("目前 cluster 不存在於 cluster_behavior 中，請重新確認模型與資料是否一致。")
    st.stop()

user_recs = get_cluster_only_recommendations(
    cluster_id=cluster_id,
    top_k=top_k,
    cluster_behavior=cluster_behavior,
    attractions_df=attractions
)

if len(user_recs) == 0:

    st.warning("此 cluster 沒有推薦結果。")

else:

    display_cols = [
        "scene_name",
        "name",
        "attraction_type",
        "recommendation_score",
        "cluster_score",
        "cost_level",
        "indoor_score",
        "photo_value",
        "nature_value",
        "culture_value",
        "food_value",
        "popularity",
        "estimated_time"
    ]

    display_cols = [
        col for col in display_cols
        if col in user_recs.columns
    ]

    st.dataframe(
        user_recs[display_cols],
        width="stretch"
    )

    st.caption(
        "scene_name 是為了展示用途產生的現實場景式名稱；name 保留為系統內部產生的景點代碼。"
    )

    st.markdown("### 推薦結果解釋")

    for _, row in user_recs.iterrows():

        with st.expander(f"{row.get('scene_name', row['name'])}"):

            st.write(f"場景名稱：{row.get('scene_name', row['name'])}")
            st.write(f"內部名稱：{row['name']}")
            st.write(f"景點類型：{row.get('attraction_type', 'N/A')}")
            st.write(f"Cluster Score：{row['cluster_score']:.4f}")
            st.write(
                "解釋：此推薦是將景點特徵向量與該 cluster 的平均行為特徵向量進行相似度比較。"
            )


# =========================
# Cluster Interpretation
# =========================

st.subheader("Cluster 解釋")

cluster_id = int(selected_user["soft_cluster"])

st.markdown(f"### {format_cluster_title(cluster_id)}")
st.write(get_cluster_description(cluster_id))

if cluster_interpretation is not None:

    cluster_info = cluster_interpretation[
        cluster_interpretation["cluster"] == cluster_id
    ].copy()

    if len(cluster_info) > 0:

        cluster_info["feature_name"] = cluster_info["feature"].map(
            FEATURE_DISPLAY_NAMES
        ).fillna(cluster_info["feature"])

        high_features = cluster_info[
            cluster_info["direction"] == "high"
        ].sort_values("z_mean", ascending=False)

        low_features = cluster_info[
            cluster_info["direction"] == "low"
        ].sort_values("z_mean", ascending=True)

        col1, col2 = st.columns(2)

        with col1:

            st.markdown("#### 高於平均的特徵")

            st.dataframe(
                high_features[["feature_name", "feature", "z_mean"]],
                width="stretch",
                hide_index=True
            )

        with col2:

            st.markdown("#### 低於平均的特徵")

            st.dataframe(
                low_features[["feature_name", "feature", "z_mean"]],
                width="stretch",
                hide_index=True
            )

        st.caption(
            "z_mean 是標準化後的群體平均值；正值代表相對整體偏高，負值代表相對整體偏低。"
        )

    else:

        st.info("找不到此 cluster 的解釋資料。")

else:

    st.info("尚未找到 soft_cluster_interpretation.csv。可先執行 cluster_interpretation_soft.py。")


# =========================
# Method Comparison
# =========================

st.subheader("推薦方法比較")

if method_comparison is not None:

    st.dataframe(
        method_comparison,
        width="stretch"
    )

    best_row = method_comparison.sort_values(
        "mean_similarity",
        ascending=False
    ).iloc[0]

    st.write(
        f"目前最佳方法：{best_row['method']}，"
        f"Mean Similarity = {best_row['mean_similarity']:.4f}，"
        f"Lift = {best_row['recommendation_lift']:.4f}"
    )

else:

    st.info("尚未找到 recommendation_method_comparison.csv。可先執行 evaluate_clusters.py。")


# =========================
# Figures
# =========================

st.subheader("分析圖表")

figure_paths = [
    ("推薦方法比較", "figures/recommendation_method_comparison.png"),
    ("Soft Cluster Heatmap", "figures/soft_cluster_feature_heatmap.png"),
    ("Soft Cluster Confidence", "figures/soft_cluster_confidence_distribution.png"),
    ("Correlation Matrix", "figures/correlation_matrix.png"),
]

for title, path in figure_paths:

    if os.path.exists(path):

        with st.expander(title):

            st.image(
                path,
                width="stretch"
            )


# =========================
# Footer
# =========================

st.divider()

st.markdown(
    """
### 系統流程

使用者輸入條件  
→ Soft Clustering  
→ 得到 Cluster、Confidence 與 Probability  
→ 判讀模型信心與可能的不確定性  
→ 使用 Cluster 平均行為特徵  
→ Cluster-based 景點推薦  
→ 推薦方法比較
"""
)